package.json
newly released typescript package v2.4.1 is not working so we're bumping ts-node to version 3 to fix it
Context:
Microsoft/TypeScript#16772
=> bump ts-node to version 3 for app template-frontend

circle.yml
Nowadays it more surprising if a repo doesn't use dapple.
cc @nathanleiby
=> Added dapple deploys

package.json
There was a bug in clever-frontend-utils with AsyncListReducers that was fixed in version 1.2.1. This bumps the version in the package.json to make sure the new fixed version gets pulled in.
=> Bump frontend-utils version to 1.2.1 minimum to get bug fix

launch/template-frontend.yml
0.1 cpu/mem is not enough to support the node process. Bump it up to 0.5
The https expose was causing issues with port conflicts. Remove it.
=> Remove https expose and bump up default resources

types/function/index.d.ts
I noticed in Launchpad that our Function interface extension can allow non-existent props to be passed into components https://github.com/Clever/launchpad/pull/2991
Let's remove it from template-frontend as well!
=> Remove Function type which can cause components to accept non-existent props

.circleci/config.yml, .github/CODEOWNERS, .github/pull_request_template.md
[Link to JIRA](https://clever.atlassian.net/browse/INFRANG-3723)
Let's move new repos to use this workflow-style Circle config. Some advantages are that publishing can happen at the same time as testing, and that it is easier to rerun individual pieces when there are failures.
Based on https://github.com/Clever/cil-event-logs-service/pull/102
-----
Also adding CODEOWNERS for autoassignment, and some "first-time" steps to the PR template.
=> move to circle workflow

src/server/app/app.ts, src/server/lib/helpers.ts, src/server/middleware/csrfProtectionMiddleware.ts, src/server/middleware/index.ts
[SEC-810](https://clever.atlassian.net/browse/SEC-810)
Add CSRF protection middleware (using origin checking) to frontend-template as follow for [FLARE-827](https://clever.atlassian.net/browse/FLARE-827)
tested by doing the following:
- initialized a new app with ark using the existing frontend-template, manually copied over the [csrf middleware changes](https://github.com/Clever/frontend-csrf-test-app/compare/csrf-middleware-testing) that are in this PR, and deployed the app to a dev environment with a `int.clever.com` domain. 
- created two routes to `GET` and `POST` where get would increment a counter variable that was kept in a user session with [express-session](https://www.npmjs.com/package/express-session).
- created a simple web page app hosted externally by …
=> SEC-810 Add CSRF middleware

kvconfig.yml, launch/template-frontend.yml, package-lock.json, package.json, src/server/app/app.ts
I noticed a few errors when trying to run the template via `make run` (what `ark start -l` calls under the hood).
On the server:
```
Error: ENOENT: no such file or directory, open '/Users/arsalan/go/src/github.com/Clever/template-frontend/src/server/app/kvconfig.yml'
```
On the client:
```
ERROR in ./node_modules/react-linkify/dist/Linkify.js
Module not found: Error: Can't resolve 'file-loader' in '/Users/arsalan/go/src/github.com/Clever/template-frontend'
```
This PR addresses both of the above to get the template running again.
=> Get template running again

.circleci/config.yml, webpack.config.js
This PR adds support for CDN-served assets! It has always pained me that the template-frontend doesn't make this easy and that, as a result, many of our frontend services have gone without CDN-served assets for years (e.g. sd2).
For context, our frontend servers can serve JS and CSS bundles on their own. But this puts load on our frontend servers (these files can be massive compared to JSON API responses) and can also make for a slower user experience. By publishing assets to a CDN (content delivery network) and having the CDN serve them, we offload the work of serving assets and also use a geographically distributed system designed for fast asset delivery.
-----
A port of the changes in https://github.com/Clever/family-portal/pull/61 and https://github.com/Clever/family-portal/pull/93
=> Add support for CDN-served assets

src/server/config.ts, src/server/lib/Clients.ts
This PR makes it easier to load/mock clients/libs on the Clients class, while also maintaining good typing. It's a port of https://github.com/Clever/family-portal/pull/22. See that PR for more context!
=> Make it easier to load/mock clients/libs on the Clients class

package-lock.json, package.json, src/server/app/app.ts, src/server/app/errors/errorHandler.ts, src/server/config.ts, src/server/lib/logging/index.ts, src/server/lib/logging/requestExtractors.ts, src/server/middleware/bodyParserErrorHandler.ts
This PR updates the template-frontend's global middlewares, porting over a number of changes from FamPo. These updates include:
- Handling errors from the body-parser middleware (https://github.com/Clever/family-portal/pull/104)
- Configuring the health check as a short-circuiting middleware (a common practice in our frontend servers to ensure that the health check is as lightweight as possible) (part of https://github.com/Clever/family-portal/pull/88)
- Adding a middleware to auto-redirect from http to https (unless running locally) (https://github.com/Clever/family-portal/pull/88)
- Adding a middleware to handle malformed paths (https://github.com/Clever/family-portal/pull/107)
- Adding Kayvee middleware for request-finished logs and a `req.log` logger …
=> Update global middlewares

.circleci/config.yml, .npmrc_docker
For every new frontend repo, we have to make some tweaks to grant CircleCI the ability to install private dependencies, e.g. https://github.com/Clever/family-portal/commit/9fbb55f7251d24a99163d79b35c9f3fc57dfdab2. Let's bake these tweaks into the template so that engineers don't have to make them.
The tweaks mirror Infra's [instructions here](https://clever.atlassian.net/wiki/spaces/ENG/pages/106566084/Build+System#BuildSystem-Installingaprivatepackage).
=> Grant CircleCI the ability to install private dependencies

package-lock.json, package.json, src/server/config.ts, tsconfig.json, types/placeholder/index.d.ts
Ports the changes from https://github.com/Clever/family-portal/pull/212 to the template-frontend. Namely, it switches to using the new version of `clever-discovery` with types and removes an unnecessary `allowSyntheticDefualtImports`.
=> Use typed discovery

.circleci/config.yml, launch/template-frontend.yml
https://clever.atlassian.net/browse/INFRANG-4341
Setting the new `deploy_config` in the launch yml, and removing that content from the CI config
Only template-wag and template-frontend have `canaryInProd` set to true
=> deploy config

launch/template-frontend.yml
**JIRA:** https://clever.atlassian.net/browse/INFRANG-5111
**Overview:**
In this PR we will migrate all internal single region services in this repo to use app mesh to hybrid state.
After this PR is merged the workers will have both envoy proxy sidecar and other appmesh constructs as well as a loadbalancers. Other services/workers have the option to use either option for making connections.
Eventually all services and workers will be restarted to make it so that all traffic comes through envoy at which point we will migrate this service to mesh_only
**Rollout:**
- monitor cpu and memory
- if upstream is in mesh then restart them so that traffic is sent using envoy
=> migrate single-region services to app mesh in hybrid state in dev

launch/template-frontend.yml
https://clever.atlassian.net/browse/INFRANG-5475
In Mesh there is no concept of alarm source of Target, ELB and Total as all metrics are coming from envoy sidecar. We are soon going to merge a change which will block CI for applications if source field is present for InternalErrorAlarms and mesh_config for prod set to mesh_only.
You have to review this PR to see that the new alarms make sense. It was hard to script all the different alarm setups we have across services. In most cases I have removed duplicate alarms but you might want to remove some more alarms or keep some deleted alarms.
Merge PR and deploy via dapple.
=> clean up alarms

launch/template-frontend.yml
**Jira:** https://clever.atlassian.net/browse/INFRANG-5936
This PR migrates the app to us-west-2
Dev:
1. Deploy in us-west-2 clever-dev or dev-infra environment (merging not mandatory)
2. Restart upstream services
3. Team owners to test if dev service is functional in us-west-2
4. Kill the older deployment in us-west-1 after confirming successful deploy and traffic flow/activity
Prod:
1. Get approval from app owners
2. Deploy in us-west-2 after merging
3. Restart upstream services
4. Traffic to pods can be verified in Grafana
5. Kill the older prod deployment in us-west-1 after a minimum of 3 days only after confirming all traffic is coming thru to the new deployment
=> migrate pod config to uw2

launch/template-frontend.yml
https://clever.atlassian.net/browse/INFRANG-6012
Delete the mesh config as we are exiting mesh and this mesh_config is not used anymore.
Currently catapult is using a feature flag in place of this mesh config and the feature flag is set to "alb_only" for this app. Which means this is already running in production
Merge PR and deploy via dapple
=> remove mesh_config

package.json, src/server/config.ts
https://clever.atlassian.net/browse/INFRANG-6337
CCR is going away so apps can't really depend on CCR. But today apps don't really depend on CCR, they use `discovery(clever-com-router, external)` just to build a link which is used for redirects.
Now we are moving to a new system where the links are defined in `externalUrlUsage` in launch config of the app. 
I am updating the version of clever-discovery in our template so that new repo start off with best practices. 
This template is similar to family-portal which was tested!
#
=> move to using externalUrlUsage instead of discovery

package.json, src/server/config.ts
https://clever.atlassian.net/browse/INFRANG-6430
There was a breaking api change to clever-discovery for external_url. This PR pulls in the latest version
unit tests are good enough for this change!
deploy
=> bump version of clever-discovery

Makefile, package.json
[FEE-220]
There were two issues I encountered when using this template
`ark init -t template-frontend ...`
`[webpack-dev-server] [HPM] Error occurred while proxying request localhost:5020/ to http://localhost:5021/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)`
After some digging around, it turns out newer versions of webpack-dev-server deal with 
- https://github.com/webpack/webpack-dev-server/issues/4828 
- https://github.com/chimurai/http-proxy-middleware#nodejs-17-econnrefused-issue-with-ipv6-and-localhost-705 
So the fix was to update webpack to more recent versions.
.. which causes the loading of locahost:5021 to fail b/c there’s nothing in /build/...pug-stuff 
So the fix was to modify the run target to build after cleaning
```
build: clean …
```
=> fix: Makefile's run target to not prematurely clean the /build folder
